### ISSUE TITLE
kOS Support

### ISSUE THREAD

**Issue by SirDiazo** [SirDiazo/AGExt#9]
Add kOS support

**Comment by SirDiazo** [comment]
done on AGX's side, next kOS release will have this. (kOS 15.5 is current version and does not support AGX, next version after that does. Not sure if it will be 15.6 or 16.0)

**Comment by erendrake** [comment]
working on this release as we speak :) would you add us to the "supported mods" on your forum thread? i should setup a similar block in our OP

**Comment by SirDiazo** [comment]
Will do.
